# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu-16.04'
  
variables:
  dockerId: 'cmendibl3'
  imageName: 'kube-sherlock:$(Build.BuildId)'

steps:
- script: |
    docker info
    docker build -t $(dockerId)/$(imageName) .
